name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/github-contribution-grid-snake.svg
            profile/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          SETTING_JSON: conf/github-profile-3d-contrib.json
          # Force output to the same directory as other stats
          OUTPUT_DIR: profile

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Al-Taie&show_icons=true&hide_rank=true&count_private=true&include_all_commits=true&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=Al-Taie&layout=donut&langs_count=8&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&hide_border=true
          path: profile/top-langs.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate CodeSignal pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=CodeSignal&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-CodeSignal.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate Marvel pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=Marvel&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-Marvel.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate MoviesApp pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=MoviesApp&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-MoviesApp.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate KanbanBoard pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=KanbanBoard&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-KanbanBoard.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate SuperHero pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=SuperHero&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-SuperHero.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate TriviaGame pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=TriviaGame&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-TriviaGame.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate Covid19Vaccine pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=Covid19Vaccine&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-Covid19Vaccine.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate Notes pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=Notes&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-Notes.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate SpendingTracker pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=SpendingTracker&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-SpendingTracker.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate quick-mailer pin
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=Al-Taie&repo=quick-mailer&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&border_radius=10
          path: profile/pin-quick-mailer.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Generate WakaTime card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: username=Al-Taie&layout=compact&bg_color=30,e96443,904e95&title_color=fff&text_color=fff&icon_color=fff&border_color=fff&hide_border=true
          path: profile/wakatime.svg
          token: ${{ secrets.PROFILE_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
